networks:
  balance-net:

volumes:
  balance-volume:

services:
  db:
    image: postgres
    container_name: balance-db
    environment:
      - TZ=Asia/Yangon
      - POSTGRES_USER=balance
      - POSTGRES_PASSWORD=balance
      - POSTGRES_DB=balance
    ports:
      - 5432:5432
    volumes:
      - balance-volume:/var/lib/postgresql/data